[pytest]
pythonpath = .
testpaths = tests
markers =
    exam_flow: ID 1부터 15까지 연속 E2E 시험 흐름
    exam_retake_flow: ID 24부터 26까지 연속 E2E 시험 재응시 흐름
    board_flow: ID 16부터 20까지 연속 E2E 게시판 흐름
    schedule_flow: ID 21부터 23까지 연속 E2E 수업 일정 흐름
    schedule_management_flow: ID 27부터 35까지 연속 E2E 수업 일정 관리 흐름
